**Warning!**

*To activate the C# kernel, follow these steps:*

* Run the code of the next cell and wait for its completion.

* Refresh the browser page (in most cases, this can be done by pressing the F5 key).

* **Run your C# cells!**

In [ ]:
#@title Prepare Google Colab for C# Kernel

# Install dotnet

!wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
!sudo dpkg -i packages-microsoft-prod.deb &> /dev/null
!rm packages-microsoft-prod.deb
!sudo apt-get update -qq &> /dev/null
!sudo apt-get install dotnet-sdk-7.0 -qq &> /dev/null

# Install jupyter kernel

!dotnet tool install -v q --tool-path /usr/bin --version 1.0.360602 Microsoft.dotnet-interactive &> /dev/null
!dotnet interactive jupyter install &> /dev/null

# Create proxy file

with open("ipc_proxy_kernel.py", "w") as f:
    f.write("""import zmq;
import json;
import argparse;
from threading import Thread;
from traitlets.traitlets import Type;
from jupyter_client import KernelClient;
from jupyter_client.session import Session;
from jupyter_client.channels import HBChannel;
from jupyter_client.manager import KernelManager;

parser = argparse.ArgumentParser();
parser.add_argument("connection_file");
parser.add_argument("--kernel", type = str, required = True);
args = parser.parse_args();

# parse connection file details
with open(args.connection_file, "r") as connection_file:
    connection_file_contents = json.load(connection_file);
    transport = str(connection_file_contents["transport"]);
    ip = str(connection_file_contents["ip"]);
    shell_port = int(connection_file_contents["shell_port"]);
    stdin_port = int(connection_file_contents["stdin_port"]);
    control_port = int(connection_file_contents["control_port"]);
    iopub_port = int(connection_file_contents["iopub_port"]);
    hb_port = int(connection_file_contents["hb_port"]);
    signature_scheme = str(connection_file_contents["signature_scheme"]);
    key = str(connection_file_contents["key"]).encode();
# channel | kernel_type | client_type
# shell   | ROUTER      | DEALER
# stdin   | ROUTER      | DEALER
# ctrl    | ROUTER      | DEALER
# iopub   | PUB         | SUB
# hb      | REP         | REQ
zmq_context = zmq.Context()

def create_and_bind_socket(port: int, socket_type: int):
    if(port <= 0):
        raise ValueError(f"Invalid port: {port}");
    if(transport == "tcp"):
        addr = f"tcp://{ip}:{port}";
    elif(transport == "ipc"):
        addr = f"ipc://{ip}-{port}";
    else:
        raise ValueError(f"Unknown transport: {transport}");
    socket: zmq.Socket = zmq_context.socket(socket_type);
    socket.linger = 1000; # ipykernel does this
    socket.bind(addr);
    return socket;

shell_socket = create_and_bind_socket(shell_port, zmq.ROUTER);
stdin_socket = create_and_bind_socket(stdin_port, zmq.ROUTER);
control_socket = create_and_bind_socket(control_port, zmq.ROUTER);
iopub_socket = create_and_bind_socket(iopub_port, zmq.PUB);
hb_socket = create_and_bind_socket(hb_port, zmq.REP);
# Proxy and the real kernel have their own heartbeats. (shoutout to ipykernel
# for this neat little heartbeat implementation)
Thread(target = zmq.device, args = (zmq.QUEUE, hb_socket, hb_socket)).start();

def ZMQProxyChannel_factory(proxy_server_socket: zmq.Socket):
    class ZMQProxyChannel(object):
        kernel_client_socket: zmq.Socket = None;
        session: Session = None;

        def __init__(self, socket: zmq.Socket, session: Session, _ = None):
            super().__init__();
            self.kernel_client_socket = socket;
            self.session = session;

        def start(self):
            # Very convenient zmq device here, proxy will handle the actual zmq
            # proxying on each of our connected sockets (other than heartbeat).
            # It blocks while they are connected so stick it in a thread.
            Thread(
                target = zmq.proxy,
                args = (proxy_server_socket, self.kernel_client_socket)
            ).start();

        def stop(self):
            if(self.kernel_client_socket is not None):
                try:
                    self.kernel_client_socket.close(linger = 0);
                except Exception:
                    pass;
                self.kernel_client_socket = None;

        def is_alive(self):
            return self.kernel_client_socket is not None;

    return ZMQProxyChannel

class ProxyKernelClient(KernelClient):
    shell_channel_class = Type(ZMQProxyChannel_factory(shell_socket));
    stdin_channel_class = Type(ZMQProxyChannel_factory(stdin_socket));
    control_channel_class = Type(ZMQProxyChannel_factory(control_socket));
    iopub_channel_class = Type(ZMQProxyChannel_factory(iopub_socket));
    hb_channel_class = Type(HBChannel);


kernel_manager = KernelManager();
kernel_manager.kernel_name = args.kernel;
kernel_manager.transport = "tcp";
kernel_manager.client_factory = ProxyKernelClient;
kernel_manager.autorestart = False;
# Make sure the wrapped kernel uses the same session info. This way we don't
# need to decode them before forwarding, we can directly pass everything
# through.
kernel_manager.session.signature_scheme = signature_scheme;
kernel_manager.session.key = key;
kernel_manager.start_kernel();
# Connect to the real kernel we just started and start up all the proxies.
kernel_client: ProxyKernelClient = kernel_manager.client();
kernel_client.start_channels();
# Everything should be up and running. We now just wait for the managed kernel
# process to exit and when that happens, shutdown and exit with the same code.
exit_code = kernel_manager.kernel.wait();
kernel_client.stop_channels();
zmq_context.destroy(0);
exit(exit_code);""");

# Install proxy

import os;
import sys;
import json;
import shutil;
import os.path;
from jupyter_client.kernelspec import KernelSpec, KernelSpecManager, NoSuchKernel;

kernel_spec_manager = KernelSpecManager();
real_kernel_spec: KernelSpec = kernel_spec_manager.get_kernel_spec(".net-csharp");
real_kernel_install_path = real_kernel_spec.resource_dir;
new_kernel_name = ".net-csharp_tcp";
new_kernel_install_path = os.path.join(
    os.path.dirname(real_kernel_install_path), new_kernel_name
);
shutil.move(real_kernel_install_path, new_kernel_install_path);
# Update the moved kernel name and args. We tag it _tcp because the proxy will
# impersonate it and should be the one using the real name.
new_kernel_json_path = os.path.join(new_kernel_install_path, "kernel.json");
with open(new_kernel_json_path, "r") as in_:
    real_kernel_json = json.load(in_);
    real_kernel_json["name"] = new_kernel_name;
    real_kernel_json["argv"] = list(
        map(
            lambda arg: arg.replace(real_kernel_install_path, new_kernel_install_path),
            real_kernel_json["argv"]
        )
    );
with open(new_kernel_json_path, "w") as out:
    json.dump(real_kernel_json, out);
os.makedirs(real_kernel_install_path)
proxy_kernel_implementation_path = os.path.join(
    real_kernel_install_path, "ipc_proxy_kernel.py"
);
proxy_kernel_spec = KernelSpec();
proxy_kernel_spec.argv = [
    sys.executable,
    proxy_kernel_implementation_path,
    "{connection_file}",
    f"--kernel={new_kernel_name}"
];
proxy_kernel_spec.display_name = real_kernel_spec.display_name;
proxy_kernel_spec.interrupt_mode = real_kernel_spec.interrupt_mode or "message";
proxy_kernel_spec.language = real_kernel_spec.language;
proxy_kernel_json_path = os.path.join(real_kernel_install_path, "kernel.json");
with open(proxy_kernel_json_path, "w") as out:
    json.dump(proxy_kernel_spec.to_dict(), out, indent = 2);
new_name = shutil.copy("ipc_proxy_kernel.py", proxy_kernel_implementation_path);

In [ ]:
#@title Refresh the browser page (in most cases, this can be done by pressing the F5 key)


**Helpers**

In [1]:
using System;
using System.IO;
using System.Net;

void wget(string url)
{
  using(var client = new WebClient())
  {
    client.DownloadFile(url, Path.GetFileName((new Uri(url)).LocalPath));
  }
}


(7,22): warning SYSLIB0014: 'WebClient.WebClient()' is obsolete: 'WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.'



**Download torchlite release from GitHub**

In [2]:
wget("https://github.com/ColorfulSoft/TorchLite/releases/download/Latest/torchlite.dll")

**Using directives**

In [3]:
#r "torchlite.dll"

In [4]:
using System;
using System.AI.Experimental; // for torchlite

**Example 1. Creation and output of tensors**

In [5]:
var a = torchlite.tensor(new [,]{{1, 2, 3},
                                 {4, 5, 6}}); // From .NET array
var b = torchlite.randn(3); // With normal random numbers
var c = torchlite.zeros(2, 2); // With zeros

Console.WriteLine(a); // Print torchlite.Tensor using Console.WriteLine
Console.WriteLine(b);
Console.WriteLine(c);

tensor([[1, 2, 3],
        [4, 5, 6]], dtype = torchlite.int32, requires_grad = False)
tensor([-0.0323,   0.361, -0.2495], dtype = torchlite.float32, requires_grad = False)
tensor([[0, 0],
        [0, 0]], dtype = torchlite.float32, requires_grad = False)


**Example 2. Indexing**

In [6]:
Console.WriteLine(a[0]); // Get specified dimension(s)
Console.WriteLine(a[":", 1]); // Get slice via string index
Console.WriteLine(b[new torchlite.Slice(1, 3)]); // Get slice via torchlite.Slice index

a[1] = 10;
Console.WriteLine(a);

tensor([1, 2, 3], dtype = torchlite.int32, requires_grad = False)
tensor([2, 5], dtype = torchlite.int32, requires_grad = False)
tensor([  0.361, -0.2495], dtype = torchlite.float32, requires_grad = False)
tensor([[ 1,  2,  3],
        [10, 10, 10]], dtype = torchlite.int32, requires_grad = False)


**Example 3. Type conversions**

In [7]:
var a_float = a.@float();
var c_bool = c.@bool();
Console.WriteLine(a_float);
Console.WriteLine(c_bool);

tensor([[ 1,  2,  3],
        [10, 10, 10]], dtype = torchlite.float32, requires_grad = False)
tensor([[False, False],
        [False, False]], dtype = torchlite.bool, requires_grad = False)


**Example 4. Arithmetic**

In [8]:
var left = torchlite.randn(3, 2);
var right = torchlite.randn(1, 2);
Console.WriteLine(left);
Console.WriteLine(right);
Console.WriteLine(left + right);
Console.WriteLine(left - right);
Console.WriteLine(left * right);
Console.WriteLine(left / right);
// Power is implemented through ^ (exclusive or) C# operator.
// It has lower precedence than other operations, so it should be braced.
// ^ operator implements power when at least one operand is floating point and bitwise xor otherwise.
Console.WriteLine(left ^ right);

tensor([[ 1.0971,  1.4184],
        [-1.0904,  0.5814],
        [ 0.2759, -0.2624]], dtype = torchlite.float32, requires_grad = False)
tensor([[0.0421,  0.009]], dtype = torchlite.float32, requires_grad = False)
tensor([[ 1.1391,  1.4274],
        [-1.0483,  0.5904],
        [  0.318, -0.2535]], dtype = torchlite.float32, requires_grad = False)
tensor([[  1.055,  1.4094],
        [-1.1325,  0.5724],
        [ 0.2339, -0.2714]], dtype = torchlite.float32, requires_grad = False)
tensor([[ 0.0462,  0.0127],
        [-0.0459,  0.0052],
        [ 0.0116, -0.0024]], dtype = torchlite.float32, requires_grad = False)
tensor([[  26.0787,  157.8145],
        [ -25.9197,   64.6856],
        [   6.5595,  -29.1991]], dtype = torchlite.float32, requires_grad = False)
tensor([[1.0039, 1.0031],
        [   NaN, 0.9951],
        [0.9473,    NaN]], dtype = torchlite.float32, requires_grad = False)


**Example 5. Pointwise math**

In [9]:
var a = torchlite.randn(5, 5);
Console.WriteLine(a);
Console.WriteLine(torchlite.abs(a)); // torchlite module contains many pointwise functions for tensors
Console.WriteLine(a.relu()); // Almost all functions are also available via a tensor instance.

tensor([[ 0.6179,  0.4378,   -0.03, -0.7334,  2.0564],
        [ -0.592, -1.0775,  -0.971,  1.1139, -1.5525],
        [-0.6467, -0.3437,  0.4334,  0.4379, -0.1421],
        [ 0.8032, -3.0323, -0.2757,  0.7608,  0.4507],
        [ 0.5388,  -0.766,  0.6576,  0.6573,  1.3778]], dtype = torchlite.float32, requires_grad = False)
tensor([[0.6179, 0.4378,   0.03, 0.7334, 2.0564],
        [ 0.592, 1.0775,  0.971, 1.1139, 1.5525],
        [0.6467, 0.3437, 0.4334, 0.4379, 0.1421],
        [0.8032, 3.0323, 0.2757, 0.7608, 0.4507],
        [0.5388,  0.766, 0.6576, 0.6573, 1.3778]], dtype = torchlite.float32, requires_grad = False)
tensor([[0.6179, 0.4378,      0,      0, 2.0564],
        [     0,      0,      0, 1.1139,      0],
        [     0,      0, 0.4334, 0.4379,      0],
        [0.8032,      0,      0, 0.7608, 0.4507],
        [0.5388,      0, 0.6576, 0.6573, 1.3778]], dtype = torchlite.float32, requires_grad = False)
